
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aparracorbacho
 */
public class PrincipalCorreo extends javax.swing.JFrame {
    Object []object = new Object[5];
    String usuario = null;
    DefaultTableModel modelo = new DefaultTableModel();
    MySqlC mysql = new MySqlC();
            
    public void setusuario(String usuario){
        this.usuario = usuario;
        bienvenido.setText("Bienvenido al correo interno de la empresa " +usuario);
        mysql.conn();
        cargar();
    }
    
    public void cargar(){
        try {           
            modelo.addColumn("Id");
            modelo.addColumn("Fecha");
            modelo.addColumn("Hora");
            modelo.addColumn("Enviado por");
            modelo.addColumn("Titulo");
           
            String sqlcargar = "Select * from correos where recibidop = '"+usuario+"' ORDER BY id DESC";
            ResultSet rs = mysql.consulta(sqlcargar);
            while(rs.next()){
                object[0] = rs.getInt(1);  
                object[1] = rs.getString(6);
                object[2] = rs.getString(7);
                object[3] = rs.getString(2);
                object[4] = rs.getString(4);
                modelo.addRow(object);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalCorreo.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        TCorreos.setModel(modelo);
        TCorreos.getColumnModel().getColumn(0).setMaxWidth(0);
        TCorreos.getColumnModel().getColumn(0).setMinWidth(0);
        TCorreos.getColumnModel().getColumn(0).setPreferredWidth(0);
        TCorreos.getColumnModel().getColumn(1).setMaxWidth(90);
        TCorreos.getColumnModel().getColumn(1).setMinWidth(90);
        TCorreos.getColumnModel().getColumn(2).setMaxWidth(70);
        TCorreos.getColumnModel().getColumn(2).setMinWidth(70);
        TCorreos.getColumnModel().getColumn(3).setMaxWidth(120);
        TCorreos.getColumnModel().getColumn(3).setMinWidth(120);
        
            for (int i = 0;i<TCorreos.getColumnCount();i++){
            TCorreos.getColumnModel().getColumn(i).setResizable(false);
            }
    }
    
    
    
    /**
     * Creates new form PrincipalCorreo
     */
    public PrincipalCorreo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenido = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TCorreos = new javax.swing.JTable();
        Salir = new javax.swing.JButton();
        escirbircorreo = new javax.swing.JButton();
        exportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal - Correo");

        bienvenido.setText("Bienvenido al correo interno de la empresa");

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        TCorreos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TCorreos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TCorreosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TCorreos);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        escirbircorreo.setText("Escribir correo");
        escirbircorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escirbircorreoActionPerformed(evt);
            }
        });

        exportar.setText("Exportar Correos");
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escirbircorreo)
                        .addGap(65, 65, 65)
                        .addComponent(exportar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bienvenido)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actualizar)
                            .addComponent(Salir))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bienvenido)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(escirbircorreo)
                            .addComponent(exportar))
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        cargar();
    }//GEN-LAST:event_actualizarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        mysql.close();
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void TCorreosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TCorreosMouseClicked
        // TODO add your handling code here:
        
         // Doble click en cada correo
        JTable target = (JTable)evt.getSource();
        int row = target.getSelectedRow();
        int valor = (int) TCorreos.getValueAt(row, 0);
        VerCorreo vercorreo = new VerCorreo();
        vercorreo.setValores(valor);
        vercorreo.setVisible(true);
               
    }//GEN-LAST:event_TCorreosMouseClicked

    private void escirbircorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escirbircorreoActionPerformed
        // TODO add your handling code here:
        EscribirCorreo escribirn = new EscribirCorreo();
        escribirn.setUsuario(usuario);
        escribirn.setVisible(true);
    }//GEN-LAST:event_escirbircorreoActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        // Codigo para exportar correos
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
        String correoexportado = "src/exportado/Correos.txt";
        fichero = new FileWriter(correoexportado);
        String fileLocal = new String(correoexportado);
        ResultSet rs = null;
        rs = mysql.consulta("Select * from correos where recibidop = '"+usuario+"' ");

        while (rs.next()){
               pw = new PrintWriter(fichero);
               pw.println("#Titulo: " + rs.getString(4));
               pw.println("#Enviado por: " + rs.getString(2));
               pw.println("#Fecha y hora: "+rs.getString(6) + " " +rs.getString(7));
               pw.println("#Contenido:\n" + rs.getString(5));
               pw.println("#######################################################\n");
        }
        JOptionPane.showMessageDialog(null, "Fichero exportado correctamente, acepta para abrir" , "Exportacion correcta",JOptionPane.PLAIN_MESSAGE);
        Runtime.getRuntime().exec("cmd /c start "+fileLocal);
        }catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage() , "Error" ,JOptionPane.ERROR_MESSAGE);
        } finally {
           try {
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              JOptionPane.showMessageDialog(null, e2.getMessage() , "Error",JOptionPane.ERROR_MESSAGE);
           }
        }
    
    }//GEN-LAST:event_exportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JTable TCorreos;
    private javax.swing.JButton actualizar;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton escirbircorreo;
    private javax.swing.JButton exportar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
