
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aparracorbacho
 */
public class VerCorreo extends javax.swing.JFrame {
    String enviadop, asunto, texto;
    String usuario;
    int id;
    MySqlC mysql = new MySqlC();
    
    /**
     * Creates new form VerCorreo
     */
    public VerCorreo() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(VerCorreo.DISPOSE_ON_CLOSE);
        mysql.conn();
    }
    
     public void setValores(String usuario, String enviadop, String asunto, String texto, int id){
        this.id = id;
        this.enviadop= enviadop;
        this.asunto = asunto;
        this.texto = texto;
        this.usuario = usuario;
        enviadoLabel.setText(enviadop);
        asuntoLabel.setText(asunto);
        contenidoField.setText(texto);
        contenidoField.setEditable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enviadoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        asuntoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salirdecorreo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenidoField = new javax.swing.JTextArea();
        Responder = new javax.swing.JButton();
        exportar = new javax.swing.JButton();
        borrarcorreo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ver Correo - Correo");

        jLabel1.setText("Enviado por:");

        enviadoLabel.setText("Enviado");

        jLabel2.setText("Asunto:");

        asuntoLabel.setText("Asunto");

        jLabel3.setText("Contenido:");

        salirdecorreo.setText("Salir de este correo");
        salirdecorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirdecorreoActionPerformed(evt);
            }
        });

        contenidoField.setColumns(20);
        contenidoField.setRows(5);
        jScrollPane1.setViewportView(contenidoField);

        Responder.setText("Responder");
        Responder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponderActionPerformed(evt);
            }
        });

        exportar.setText("Exportar Correo");
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });

        borrarcorreo.setText("Borrar");
        borrarcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarcorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enviadoLabel)
                            .addComponent(asuntoLabel)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(exportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(salirdecorreo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Responder)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(borrarcorreo)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enviadoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(asuntoLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Responder)
                        .addGap(29, 29, 29)
                        .addComponent(borrarcorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirdecorreo)
                    .addComponent(exportar))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirdecorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirdecorreoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirdecorreoActionPerformed

    private void ResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponderActionPerformed
        // TODO add your handling code here:
        EscribirCorreo escribir = new EscribirCorreo();
        escribir.setValores(usuario, enviadop, asunto, texto);
        escribir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResponderActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        // Codigo para exportar correo
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {   
            String correoexportado = "src/exportado/" + asunto.replace(" ","").replace(":","_") + ".txt";
            fichero = new FileWriter(correoexportado);
            String fileLocal = new String(correoexportado);
             ResultSet rs = null;
             rs = mysql.consulta("Select * from correos where id = '"+id+"' ");
              while (rs.next()){
               pw = new PrintWriter(fichero);
               pw.println("#Titulo: " + rs.getString(4));
               pw.println("#Enviado por: " + rs.getString(2));
               pw.println("#Contenido:\n" + rs.getString(5));
               pw.println("#######################################################\n");
              }
            JOptionPane.showMessageDialog(null, "Fichero exportado correctamente, acepta para abrir" , "Exportacion correcta",JOptionPane.PLAIN_MESSAGE);
            Runtime.getRuntime().exec("cmd /c start "+fileLocal);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage() , "Error",JOptionPane.ERROR_MESSAGE);
        } finally {
           try {
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              JOptionPane.showMessageDialog(null, e2.getMessage() , "Error",JOptionPane.ERROR_MESSAGE);
           }
        }
    
    }//GEN-LAST:event_exportarActionPerformed

    private void borrarcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarcorreoActionPerformed
        // Borrar correo
      int resp =JOptionPane.showConfirmDialog(null,"Seguro que quieres borrar el correo");
      if (JOptionPane.OK_OPTION == resp){
      mysql.accion("delete from correos where id = '"+id+"' ");
      JOptionPane.showMessageDialog(null, "Correo borrado con exito" , "Correo borrado",JOptionPane.INFORMATION_MESSAGE);
      mysql.close();
      this.dispose();
      } 
    }//GEN-LAST:event_borrarcorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Responder;
    private javax.swing.JLabel asuntoLabel;
    private javax.swing.JButton borrarcorreo;
    private javax.swing.JTextArea contenidoField;
    private javax.swing.JLabel enviadoLabel;
    private javax.swing.JButton exportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salirdecorreo;
    // End of variables declaration//GEN-END:variables
}
